VIA_ENABLE = yes
VIAL_ENABLE = yes

BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
MAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
RGBLIGHT_ENABLE = yes

# Reduce firmware size:
LTO_ENABLE = yes
CAPS_WORD_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE  = no
LAYER_LOCK_ENABLE = no
MUSIC_ENABLE = no
REPEAT_KEY_ENABLE = no
